import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Feather } from "@expo/vector-icons";
import { colors, type } from "@/src/theme/tokens";
import { mobileClient } from "@/src/features/mobile-client";
import type { ActiveMember, DirectMessage, MessagePerson } from "@/src/features/models";

export default function MessagesScreen() {
  const [people,setPeople]=useState<MessagePerson[]>([]); const [blocked,setBlocked]=useState<string[]>([]); const [member,setMember]=useState<ActiveMember | null>(null); const [contact,setContact]=useState<MessagePerson | null>(null); const [conversation,setConversation]=useState(""); const [messages,setMessages]=useState<DirectMessage[]>([]); const [body,setBody]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{const [nextPeople,nextBlocks,nextMember]=await Promise.all([mobileClient.people(),mobileClient.blockedUsers(),mobileClient.currentMember()]);setPeople(nextPeople);setBlocked(nextBlocks.map((entry)=>entry.blockedId));setMember(nextMember);}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível carregar participantes.");}finally{setLoading(false);}},[]);
  const loadThread=useCallback(async(id:string)=>{try{setMessages(await mobileClient.listMessages(id));}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível carregar a conversa.");}},[]);
  useEffect(()=>{void load();},[load]);
  const open=async(person:MessagePerson)=>{try{const id=await mobileClient.openConversation(person.id);setContact(person);setConversation(id);await loadThread(id);}catch(cause){Alert.alert("Conversa indisponível",cause instanceof Error?cause.message:"Não foi possível abrir a conversa.");}};
  const send=async()=>{if(!body.trim()||!conversation)return;try{await mobileClient.sendMessage(conversation,body);setBody("");await loadThread(conversation);}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível enviar a mensagem.");}};
  const toggleBlock=async(userId:string,active:boolean)=>{try{if(active)await mobileClient.unblockUser(userId);else await mobileClient.blockUser(userId);setBlocked((old)=>active?old.filter((id)=>id!==userId):[...old,userId]);if(contact?.id===userId){setContact(null);setConversation("");setMessages([]);}}catch(cause){Alert.alert("Não foi possível atualizar bloqueio",cause instanceof Error?cause.message:"Tente novamente.");}};
  if(contact)return <View style={styles.page}><View style={styles.threadHead}><Pressable onPress={()=>{setContact(null);setConversation("");}}><Feather name="arrow-left" size={20} color={colors.ink}/></Pressable><View style={styles.threadAvatar}><Text style={styles.threadInitials}>{contact.initials}</Text></View><View style={{flex:1}}><Text style={styles.threadName}>{contact.name}</Text><Text style={styles.threadSub}>Conversa privada · mesma turma</Text></View><Pressable onPress={()=>void toggleBlock(contact.id,false)}><Feather name="slash" size={19} color={colors.danger}/></Pressable></View><FlatList data={messages} keyExtractor={(item)=>item.id} contentContainerStyle={styles.thread} renderItem={({item})=><View style={[styles.bubble,item.senderId===member?.id&&styles.mine]}><Text style={[styles.messageText,item.senderId===member?.id&&styles.mineText]}>{item.body}</Text><Text style={[styles.messageTime,item.senderId===member?.id&&styles.mineTime]}>{item.createdAt}</Text></View>} ListEmptyComponent={<Text style={styles.emptyThread}>Comece uma conversa privada com {contact.name}.</Text>}/><View style={styles.composer}><TextInput value={body} onChangeText={setBody} style={styles.input} placeholder="Escreva uma mensagem" placeholderTextColor="#928C80"/><Pressable disabled={!body.trim()} onPress={()=>void send()} style={[styles.send,!body.trim()&&styles.disabled]}><Feather name="send" size={17} color="white"/></Pressable></View></View>;
  return <View style={styles.page}><Text style={styles.title}>Mensagens</Text><Text style={styles.copy}>Converse de forma privada com participantes ativos da sua turma.</Text>{loading?<ActivityIndicator color={colors.goldDark}/>:<FlatList data={people} keyExtractor={(item)=>item.id} contentContainerStyle={styles.list} renderItem={({item})=>{const isBlocked=blocked.includes(item.id);return <View style={styles.person}><Pressable onPress={()=>!isBlocked&&void open(item)} style={styles.personMain}><View style={styles.avatar}><Text style={styles.initials}>{item.initials}</Text></View><View style={{flex:1}}><Text style={styles.name}>{item.name}</Text><Text style={styles.personSub}>{isBlocked?"Usuário bloqueado":"Iniciar conversa privada"}</Text></View></Pressable><Pressable onPress={()=>void toggleBlock(item.id,isBlocked)} style={styles.block}><Feather name={isBlocked?"check-circle":"slash"} size={17} color={isBlocked?colors.success:colors.danger}/></Pressable></View>;}} ListEmptyComponent={<View style={styles.empty}><Feather name="users" size={26} color={colors.goldDark}/><Text style={styles.emptyTitle}>Nenhum contato disponível</Text><Text style={styles.emptyCopy}>Participantes ativos da sua turma aparecerão aqui.</Text></View>}/>}<View style={styles.notice}><Feather name="lock" color={colors.goldDark} size={18}/><Text style={styles.noticeText}>Ao bloquear alguém, a conversa e o conteúdo entre vocês deixam de ficar disponíveis.</Text></View>{error?<Text style={styles.error}>{error}</Text>:null}</View>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.paper,padding:20},title:{fontFamily:type.display,fontSize:32,fontWeight:"700",letterSpacing:-1,color:colors.ink},copy:{fontSize:13,lineHeight:19,color:colors.muted,marginTop:7,marginBottom:26},list:{borderTopWidth:1,borderTopColor:colors.line},person:{minHeight:64,borderBottomWidth:1,borderBottomColor:colors.line,flexDirection:"row",alignItems:"center"},personMain:{flex:1,flexDirection:"row",gap:10,alignItems:"center",paddingVertical:12},avatar:{width:38,height:38,borderRadius:19,backgroundColor:"#E8C47C",alignItems:"center",justifyContent:"center"},initials:{fontWeight:"800",fontSize:10},name:{fontSize:12,fontWeight:"800",color:colors.ink},personSub:{fontSize:10,color:colors.muted,marginTop:4},block:{padding:10},notice:{marginTop:22,backgroundColor:colors.softGold,borderWidth:1,borderColor:"#EADBB4",padding:14,flexDirection:"row",gap:8},noticeText:{fontSize:11,lineHeight:17,color:"#5F553C",flex:1},empty:{paddingVertical:40,alignItems:"center",gap:8},emptyTitle:{fontFamily:type.display,fontSize:21,fontWeight:"700",color:colors.ink},emptyCopy:{fontSize:12,lineHeight:18,color:colors.muted,textAlign:"center"},error:{color:colors.danger,fontSize:11,lineHeight:16,marginTop:12},threadHead:{flexDirection:"row",alignItems:"center",gap:10,borderBottomWidth:1,borderBottomColor:colors.line,paddingBottom:14},threadAvatar:{width:34,height:34,borderRadius:17,backgroundColor:"#E8C47C",alignItems:"center",justifyContent:"center"},threadInitials:{fontSize:10,fontWeight:"800"},threadName:{fontSize:12,fontWeight:"800",color:colors.ink},threadSub:{fontSize:9,color:colors.muted,marginTop:2},thread:{paddingVertical:18,gap:10,flexGrow:1},bubble:{maxWidth:"80%",alignSelf:"flex-start",backgroundColor:"#F4F0E8",padding:11},mine:{alignSelf:"flex-end",backgroundColor:colors.ink},messageText:{fontSize:12,lineHeight:17,color:colors.ink},mineText:{color:"white"},messageTime:{fontSize:9,color:colors.muted,marginTop:5},mineTime:{color:"#C9C2B5"},emptyThread:{color:colors.muted,textAlign:"center",paddingTop:30,fontSize:12},composer:{height:50,borderTopWidth:1,borderTopColor:colors.line,flexDirection:"row",gap:8,alignItems:"center",paddingTop:8},input:{flex:1,height:41,borderWidth:1,borderColor:colors.line,backgroundColor:colors.card,paddingHorizontal:10,fontSize:12,color:colors.ink},send:{width:41,height:41,backgroundColor:colors.ink,alignItems:"center",justifyContent:"center"},disabled:{opacity:.4}});
