import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Stack, router } from "expo-router";
import * as ImagePicker from "expo-image-picker";
import { Feather } from "@expo/vector-icons";
import { mobileClient } from "@/src/features/mobile-client";
import { colors, type } from "@/src/theme/tokens";

export default function PublishScreen() {
  const [title,setTitle]=useState(""); const [context,setContext]=useState(""); const [question,setQuestion]=useState(""); const [accepted,setAccepted]=useState(false); const [mediaUri,setMediaUri]=useState<string>(); const [busy,setBusy]=useState(false);
  const chooseMedia = async () => { try { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { Alert.alert("Permissão necessária", "Permita o acesso às fotos para anexar uma imagem clínica já anonimizada."); return; } const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes:["images"], quality:.8 }); if (!result.canceled) setMediaUri(result.assets[0]?.uri); } catch { Alert.alert("Não foi possível abrir as fotos", "Tente novamente para selecionar uma imagem."); } };
  const publish = async () => { if (!title.trim() || !context.trim() || !question.trim() || !accepted) return; setBusy(true); try { await mobileClient.publishCase({title,context,question,mediaUri}); router.replace("/(tabs)/cases"); } catch (cause) { Alert.alert("Não foi possível publicar", cause instanceof Error ? cause.message : "Tente novamente em instantes."); } finally { setBusy(false); } };
  return <><Stack.Screen options={{headerShown:true,title:"Publicar caso",presentation:"modal"}} /><ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.title}>Comece uma discussão{`\n`}com contexto.</Text><Text style={styles.copy}>Não inclua dados que identifiquem o paciente. Revise as informações antes de publicar.</Text><Field label="Título do caso" value={title} onChangeText={setTitle} placeholder="Ex.: Persistência de edema no terço medial" /><Field label="Contexto clínico" value={context} onChangeText={setContext} placeholder="Apresente o caso com dados já anonimizados." multiline /><Field label="Pergunta à comunidade" value={question} onChangeText={setQuestion} placeholder="O que você gostaria de discutir?" multiline /><Pressable accessibilityRole="button" accessibilityLabel={mediaUri ? "Trocar mídia anexada" : "Anexar mídia clínica anonimizada"} style={styles.media} onPress={() => void chooseMedia()}><Feather name="paperclip" size={18} color="#6A5729" /><View><Text style={styles.mediaTitle}>{mediaUri ? "Mídia selecionada" : "Anexar mídia"}</Text><Text style={styles.mediaCopy}>Imagem clínica anonimizada · validação no envio</Text></View></Pressable><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: accepted }} onPress={() => setAccepted((value)=>!value)} style={styles.consent}><Feather name={accepted ? "check-square" : "square"} size={20} color={accepted ? colors.goldDark : "#7F786B"} /><Text style={styles.consentText}>Confirmo que o conteúdo está anonimizado e que tenho base legal para uso educacional.</Text></Pressable><Pressable accessibilityRole="button" accessibilityState={{ disabled: busy || !title.trim() || !context.trim() || !question.trim() || !accepted }} disabled={busy || !title.trim() || !context.trim() || !question.trim() || !accepted} onPress={() => void publish()} style={[styles.publish, (busy || !title.trim() || !context.trim() || !question.trim() || !accepted) && styles.disabled]}><Text style={styles.publishText}>{busy ? "Publicando…" : "Publicar caso"}</Text><Feather name="send" size={17} color="white" /></Pressable></ScrollView></>;
}
function Field(props:{label:string;value:string;onChangeText:(value:string)=>void;placeholder:string;multiline?:boolean}) { return <View style={styles.field}><Text style={styles.label}>{props.label}</Text><TextInput {...props} accessibilityLabel={props.label} style={[styles.input, props.multiline && styles.textarea]} placeholderTextColor="#9A9489" textAlignVertical="top" /></View>; }
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.paper},content:{padding:20,paddingBottom:42},title:{fontFamily:type.display,fontSize:31,lineHeight:34,fontWeight:"700",letterSpacing:-1,color:colors.ink},copy:{fontSize:13,lineHeight:20,color:colors.muted,marginTop:13,marginBottom:27},field:{marginBottom:17},label:{fontSize:12,fontWeight:"800",color:colors.ink,marginBottom:8},input:{minHeight:48,backgroundColor:colors.card,borderWidth:1,borderColor:colors.line,padding:12,fontSize:13,color:colors.ink},textarea:{minHeight:100},media:{borderWidth:1,borderStyle:"dashed",borderColor:"#D6BD7F",backgroundColor:"#FCF8ED",padding:14,flexDirection:"row",gap:10,alignItems:"center"},mediaTitle:{fontSize:12,fontWeight:"800",color:"#4B4028"},mediaCopy:{fontSize:10,color:"#6A5729",marginTop:3},consent:{flexDirection:"row",gap:10,alignItems:"flex-start",marginTop:20},consentText:{fontSize:12,lineHeight:18,color:"#554E42",flex:1},publish:{height:52,backgroundColor:colors.ink,marginTop:25,alignItems:"center",justifyContent:"center",flexDirection:"row",gap:8},disabled:{opacity:.4},publishText:{color:"white",fontWeight:"800",fontSize:13}});
