import { useEffect, useState } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { Stack, useLocalSearchParams } from "expo-router";
import { Feather } from "@expo/vector-icons";
import { mobileClient } from "@/src/features/mobile-client";
import type { ClinicalCase } from "@/src/features/models";
import { colors, type } from "@/src/theme/tokens";

export default function CaseDetailScreen() {
  const { id } = useLocalSearchParams<{id:string}>(); const [item, setItem] = useState<ClinicalCase>();
  useEffect(() => { void mobileClient.listCases().then((items) => setItem(items.find((current) => current.id === id))); }, [id]);
  return <><Stack.Screen options={{ headerShown:true, title:"Leitura do caso", headerBackTitle:"Casos" }} /><ScrollView style={styles.page} contentContainerStyle={styles.content}>{item ? <><Text style={styles.code}>{item.code}</Text><Text style={styles.title}>{item.title}</Text><View style={styles.author}><View style={styles.avatar}><Text style={styles.avatarText}>{item.initials}</Text></View><View><Text style={styles.authorName}>{item.author}</Text><Text style={styles.time}>{item.createdAt} · Roteiro clínico</Text></View></View><View style={styles.discussion}><Text style={styles.label}>O QUE ESTÁ EM DISCUSSÃO</Text><Text style={styles.question}>{item.question}</Text></View><Text style={styles.body}>{item.excerpt}</Text><View style={styles.summary}><View style={styles.summaryHead}><Feather name="check-circle" color={colors.success} size={18} /><Text style={styles.summaryTitle}>Espaço para síntese do mentor</Text></View><Text style={styles.summaryCopy}>As conclusões supervisionadas desta discussão aparecem aqui quando o caso for resolvido.</Text></View><View style={styles.comments}><Text style={styles.commentsTitle}>Discussão</Text><Text style={styles.commentsCopy}>{item.comments} contribuições da turma</Text></View></> : <Text style={styles.empty}>Caso não encontrado.</Text>}</ScrollView></>;
}
const styles = StyleSheet.create({page:{flex:1,backgroundColor:colors.paper},content:{padding:20,paddingBottom:42},code:{fontSize:10,fontWeight:"800",letterSpacing:1,color:"#92712E"},title:{fontFamily:type.display,fontSize:31,lineHeight:34,fontWeight:"700",letterSpacing:-1,color:colors.ink,marginTop:13},author:{flexDirection:"row",gap:10,alignItems:"center",paddingVertical:20,borderBottomWidth:1,borderBottomColor:colors.line},avatar:{width:37,height:37,borderRadius:19,alignItems:"center",justifyContent:"center",backgroundColor:"#DED2B7"},avatarText:{fontSize:11,fontWeight:"700"},authorName:{fontSize:12,fontWeight:"700",color:colors.ink},time:{fontSize:10,color:colors.muted,marginTop:3},discussion:{paddingVertical:19,borderBottomWidth:1,borderBottomColor:colors.line},label:{fontSize:9,letterSpacing:.8,fontWeight:"800",color:"#92712E"},question:{fontSize:15,lineHeight:22,fontWeight:"600",color:colors.ink,marginTop:8},body:{fontSize:14,lineHeight:23,color:"#4D4A44",paddingVertical:20},summary:{backgroundColor:"#FAF6EA",borderWidth:1,borderColor:"#EADBB4",padding:15},summaryHead:{flexDirection:"row",gap:8,alignItems:"center"},summaryTitle:{fontSize:12,fontWeight:"800",color:"#3A3428"},summaryCopy:{fontSize:12,lineHeight:18,color:"#685E4B",marginTop:11},comments:{marginTop:28,paddingTop:18,borderTopWidth:1,borderTopColor:colors.line},commentsTitle:{fontFamily:type.display,fontSize:21,fontWeight:"700",color:colors.ink},commentsCopy:{fontSize:12,color:colors.muted,marginTop:5},empty:{padding:30,color:colors.muted}});
