import { Feather } from "@expo/vector-icons";
import { Pressable, StyleSheet, Text, View } from "react-native";
import type { ClinicalCase } from "@/src/features/models";
import { colors, type } from "@/src/theme/tokens";

export function CaseCard({ item, onPress }: { item: ClinicalCase; onPress: () => void }) {
  return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.top}><Text style={styles.code}>{item.code}</Text><View style={[styles.status, item.status === "resolvido" && styles.done]}><View style={styles.dot} /><Text style={styles.statusText}>{item.status === "resolvido" ? "resolvido" : "em discussão"}</Text></View></View><View style={styles.byline}><View style={styles.avatar}><Text style={styles.avatarText}>{item.initials}</Text></View><View style={styles.copy}><Text style={styles.author}>{item.author}<Text style={styles.time}> · {item.createdAt}</Text></Text><Text style={styles.title}>{item.title}</Text><Text numberOfLines={2} style={styles.excerpt}>{item.excerpt}</Text></View></View><View style={styles.question}><Text style={styles.questionLabel}>O QUE ESTÁ EM DISCUSSÃO</Text><Text style={styles.questionText}>{item.question}</Text></View><View style={styles.foot}><View style={styles.tags}>{item.tags.map((tag) => <Text key={tag} style={styles.tag}>{tag}</Text>)}</View><View style={styles.metrics}><View style={styles.metric}><Feather name="message-circle" size={14} color="#746D60" /><Text style={styles.metricText}>{item.comments}</Text></View><View style={styles.metric}><Feather name="heart" size={14} color="#746D60" /><Text style={styles.metricText}>{item.reactions}</Text></View></View></View></Pressable>;
}
const styles = StyleSheet.create({card:{backgroundColor:colors.card,borderWidth:1,borderColor:"rgba(73,64,47,.12)",padding:18,marginBottom:13,borderRadius:4},pressed:{opacity:.83,transform:[{scale:.99}]},top:{flexDirection:"row",alignItems:"center",gap:10},code:{fontSize:9,fontWeight:"700",letterSpacing:.8,color:"#92712E"},status:{flexDirection:"row",gap:5,alignItems:"center",backgroundColor:"#FBF3DC",paddingHorizontal:7,paddingVertical:4},done:{backgroundColor:"#F2EDDF"},dot:{width:5,height:5,borderRadius:3,backgroundColor:"#BA9139"},statusText:{fontSize:8,fontWeight:"800",letterSpacing:.35,color:"#8D6B28",textTransform:"uppercase"},byline:{flexDirection:"row",gap:11,marginTop:16},avatar:{width:34,height:34,borderRadius:17,backgroundColor:"#DED2B7",alignItems:"center",justifyContent:"center"},avatarText:{fontSize:10,fontWeight:"700",color:colors.ink},copy:{flex:1},author:{fontSize:11,fontWeight:"600",color:"#48433A"},time:{color:"#8A857B",fontWeight:"400"},title:{fontFamily:type.display,fontSize:20,lineHeight:23,color:colors.ink,fontWeight:"700",marginTop:5},excerpt:{fontSize:12,lineHeight:18,color:colors.muted,marginTop:6},question:{borderLeftWidth:2,borderLeftColor:colors.gold,paddingLeft:11,marginTop:16},questionLabel:{fontSize:8,color:"#92712E",fontWeight:"800",letterSpacing:.6},questionText:{fontSize:12,lineHeight:17,color:"#323232",fontWeight:"600",marginTop:5},foot:{flexDirection:"row",justifyContent:"space-between",gap:8,alignItems:"center",marginTop:16},tags:{flexDirection:"row",gap:5,flex:1,flexWrap:"wrap"},tag:{backgroundColor:"#F4F0E8",color:"#685A3E",fontSize:9,paddingHorizontal:7,paddingVertical:5},metrics:{flexDirection:"row",gap:10},metric:{flexDirection:"row",gap:4,alignItems:"center"},metricText:{fontSize:10,color:"#746D60"}});
